// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAHdoIg6ekdVk45nbgNkNhVM95uVYrVvS4",
    authDomain: "real-state-60a2b.firebaseapp.com",
    projectId: "real-state-60a2b",
    storageBucket: "real-state-60a2b.appspot.com",
    messagingSenderId: "559875065718",
    appId: "1:559875065718:web:256a1abad5df9874949c57",
    measurementId: 'G-3NCBGENBB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXh3V9Ug79shPFVnJA3P1gznnmPractWU',
    appId: '1:559875065718:android:ce49bae86d623ac6949c57',
    messagingSenderId: '559875065718',
    projectId: 'real-state-60a2b',
    storageBucket: 'real-state-60a2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAseGQxrks4didGjXfRy48DCtZhghoLWjk',
    appId: '1:559875065718:ios:ba8032b63747113a949c57',
    messagingSenderId: '559875065718',
    projectId: 'real-state-60a2b',
    storageBucket: 'real-state-60a2b.appspot.com',
    iosBundleId: 'com.example.rsAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAseGQxrks4didGjXfRy48DCtZhghoLWjk',
    appId: '1:559875065718:ios:33f94e36c4aedddf949c57',
    messagingSenderId: '559875065718',
    projectId: 'real-state-60a2b',
    storageBucket: 'real-state-60a2b.appspot.com',
    iosBundleId: 'com.example.rsAuth.RunnerTests',
  );
}
